config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # resources :categories

  get 'preview', to: 'cart#preview'
  get 'cart', to: 'cart#show'
  get 'cart_pay', to: 'cart#pay'
  get 'all_cart', to: 'cart#index'
  post 'cart/add'
  post 'cart/remove'
 
  resources :cart do
    member do
      get 'download', to: 'cart#download'
    end
  end
  resources :discounts
  resources :products do
    resources :reviews
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products do
    member do
      get 'download_pdf'
    end
  end
  root to: 'products#index'
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :Orderable
  belongs_to :product
  belongs_to :cart
end

app/models/discount_qty_module.rb
# frozen_string_literal: true

module DiscountQtyModule
  def qty_discount
    @discount_percentage=Discount.find_by(code: 'qtyp2')
    discount_percentage=@discount_percentage.discount_percentage
    if quantity > 2
      product.price * quantity - ((product.price * quantity) * discount)
    else
      product.price * quantity
    end
  end
end

app/controllers/bill_controller.rb
class BillController < ApplicationController

    def add
        @product = Product.find_by(id: params[:id])
        @cart = Cart.find_by(id: params[:id])
        quantity = params[:quantity].to_i
        current_cart = @bill.carts.find_by(product_id: @cart.id)
        if current_orderable && quantity.positive?
          current_orderable.update(quantity: quantity)
    
        else
          @bill.orderables.create(product: @product, cart: @cart, quantity: @orderable.quantity, product_name: @product.name ,customer_name: current_user.profile&.first_name,
                                  address: @orderable.address, product_price: @product.price, total_product_price: @orderable.final_price, cart: @cart.apply_discount)
        end
      end
end

app/controllers/cart_controller.rb
# frozen_string_literal: true

class CartController < ApplicationController
  def index
    @orderables = Orderable.order(created_at: :desc)
    return unless [current_user.profile&.user_id].present?

    @order_histories = Orderable.where('customer_id LIKE ?',
                                       "%#{current_user.profile&.user_id}%").order(created_at: :desc)
  end

  def show
    @render_cart = false
  end

  def add
    @product = Product.find_by(id: params[:id])
    quantity = params[:quantity].to_i
    current_orderable = @cart.orderables.find_by(product_id: @product.id)
    if current_orderable && quantity.positive?
      current_orderable.update(quantity: quantity)

    elsif quantity <= 0
      current_orderable.destroy

    else
      @cart.orderables.create(product: @product, cart_id: @cart.id, quantity: quantity, customer_name: current_user.profile&.first_name, status: 'unpaid',
                              address: current_user.profile&.address, price: @product.price, final_price: quantity * @product.price, discount: 0.0, customer_id: current_user.profile&.user_id)
    end
  end

  def remove
    Orderable.find_by(id: params[:id]).destroy
  end

  def pay
    @cart.orderables.update(discount: @cart.apply_discount, status: 'paid', updated_at: @cart.updated_at + 5.days)
    @cart.update(status: true)
   
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  before_action :load_product, only: %w[edit update show destroy download_pdf]
  before_action :authenticate_user!, except: [:index]
  layout 'new_layout', except: [:index]

  def index
    
    @products = if params[:q] && !params[:q].blank?
                  Product.matching(params[:q]).page(params[:page])
                else
                  Product.all.page(params[:page])
                end
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
     authorize @product
    if @product.save
      ProductMailer.notify_product_creation(@product.id).deliver_now
      redirect_to products_path, notice: 'New Book Added !!!'
    else
      render 'new'
    end
  end

  def edit
    authorize @product
  end

  def update
    if @product.update(product_params)
      redirect_to products_path, notice: 'Book got Updated!!!'
    else
      render 'edit'
    end
  end

  def show; end

  def destroy
    authorize @product
    @product.destroy
    redirect_to products_path, notice: 'You just Removed Book !!!'
  end

  def download_pdf
    send_file("#{Rails.root}/public/test1.txt",
              filename: "#{@product.name}.txt",
              type: 'application/txt')
  end

  private

  def product_params
    params.require(:product).permit(:name, :code, :price, :is_active, :description, :cover_image)
  end

  def load_product
    @product = Product.find(params[:id])
  end
end

app/controllers/profiles_controller.rb
# frozen_string_literal: true

class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[edit update]
  def edit; end

  def update
    if @profile.update(profile_params)
      redirect_to root_path, notice: 'Profile is successfully updated.'
    else
      render :edit
    end
  end

  private

  def set_profile
    @profile = current_user.profile || current_user.build_profile
  end

  def profile_params
    params.require(:profile).permit(:first_name)
  end
end

app/controllers/reviews_controller.rb
# frozen_string_literal: true

class ReviewsController < ApplicationController
  before_action :set_product, only: %i[new create]

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.create(review_params)
    authorize @review
    # p review.errors.full_messages.inspect
    redirect_to product_path(@product), notice: 'Thank you for your valuable review !!!'
  end

  def show; end

  def destroy
    @product = Product.find(params[:product_id])

    @review = @product.reviews.find(params[:id])
    authorize @review
    @review.destroy
    redirect_to product_path(@product), notice: 'review is deleted !!!'
  end

  private

  def set_product
    @product = Product.find(params[:product_id])
  end

  def review_params
    params.require(:review).permit(:user_name, :rating, :comments)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/bill_helper.rb
module BillHelper
end

app/helpers/cart_helper.rb
# frozen_string_literal: true

module CartHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/helpers/discount_helper.rb
# frozen_string_literal: true

module DiscountHelper
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/helpers/reviews_helper.rb
# frozen_string_literal: true

module ReviewsHelper
end

app/views/cart/_bill.html.slim
= form_with(url: cart_pay_path) do |f|
 - @cart.orderables.each do |orderable|
  - product = orderable.product
  |  <div id="
  = "cart-#{product.id}"
  | "> 
  div[style=" display:flex; justify-content:space-between: margin: 0em 5em;"]
    = f.label :Orderable_id
    = f.number_field :Orderable_id, value: orderable.id ,readonly: true,class: 'form-control form-control-sm'
    = f.label :product_id
    = f.number_field :product_id, value: orderable.product_id ,readonly: true,class: 'form-control form-control-sm'
    = f.label :cart_id
    = f.number_field :cart_id, value: orderable.cart_id ,readonly: true,class: 'form-control form-control-sm'
    = f.label :customer_name
    = f.text_field :customer_name, value: orderable.customer_name, class: 'form-control form-control-sm'
    = f.label :product_name
    = f.text_field :product_name, value: product.name, class: 'form-control form-control-sm'
    = f.label :total_product_price
    = f.number_field :total_product_price, value: orderable.price ,readonly: true,class: 'form-control form-control-sm'
    = f.label :qunatity
    = f.number_field :quantity, value: orderable.quantity ,readonly: true,class: 'form-control form-control-sm'    
    = f.label :address
    = f.text_field :address, value: orderable.address ,readonly: true,class: 'form-control form-control-sm'    
    = f.label :cart_price
    = f.number_field :cart_price, value: orderable.price ,readonly: true,class: 'form-control form-control-sm'
    / = f.submit 
  
     
    br

app/views/cart/_index_cartids_same.html.slim
h1
  | Order List
table.table.table-bordered.table-striped

    thead

      tr

        th Product Name

        th Customer Name

        th Address

        th Price

        th Quantity

        th Total payable
        th status
        th Cart id

        

    tbody
    - @orderables.each do |orderable|
        / - product = orderable.product
        tr 
            td
                strong
               
                = orderable.product.name 
            td
                strong
                
                = orderable.customer_name
            td
                strong
                
                = orderable.address
            td
                strong
                
                = orderable.price
            td
                strong
                
                =  orderable.quantity 
            td
                strong
                 
                = number_with_precision(orderable.discount, precision: 2)
            td 
                strong 
                = orderable.status
            td 
                strong 
                = orderable.cart_id
            
          
        br 
= link_to "Back" , root_path, class: "btn btn-outline-primary btn-lg"
 
            

app/views/cart/_pay.html.slim
    
        div[style="background: #ffcc66;    
            max-width: 700px;
            text-align:center;
            margin: auto;
            border-width: medium;"]
          h1 
            | pay your bills here !!!
          br  
          h3  
            | Customer Name:
            u
             = current_user.profile&.first_name 
             | &nbsp;
             = current_user.profile&.last_name
          br
          h5
                - @cart.orderables.each do |orderable|
                    - product = orderable.product
                    = product.name
                    |  * 
                    = orderable.quantity
                    
                    |  = 
                    = product.price
                    |  * 
                    = orderable.quantity
                    |  = 
                    = orderable.total 
                    |  rs 
                    p
                    
                    
          br
          br
          h3
            |  Your Total is&nbsp;
            u
             b
             =number_with_precision(@cart.total , precision: 2)
            | &nbsp; .rs
            br
          
            -if @cart.total > 2000
            | WOW!!! your cart value is more than 2000 you got 10% discount 
            br
            br
            |NOW ITS ONLY &nbsp;
            u
              b
              = number_with_precision(@cart.discount_price, precision: 2) 
            | &nbsp; .rs
          h2         
            | THANK YOU ...
            h4 
              | &emsp; visit again...
            

app/views/cart/index.html.slim
h1
  | Order List
table.table.table-bordered.table-striped

    thead

      tr

        th Product Name

        th Customer Name

        th Address

        th Price

        th Quantity

        th Total paid

        

    tbody
    - @orderables.each do |orderable|
        / - product = orderable.product
        tr 
            td
                strong
               
                = orderable.product.name 
            td
                strong
                
                = orderable.customer_name
            td
                strong
                
                = orderable.address
            td
                strong
                
                = orderable.price
            td
                strong
                
                =  orderable.quantity 
            td
                strong
                 
                = number_with_precision(orderable.total, precision: 2)
          
        br 
= link_to "Back" , root_path, class: "btn btn-outline-primary btn-lg"
 
            

app/views/cart/invoice2.html.slim
h1 Invoice

 

- if @user.profile.present?

  p Customer Name: #{@user.profile.name}

  p Billing Address: #{@user.profile.address}

  / p status: #{@status.status}

- else

  p Customer Name: N/A

 

table.table.table-bordered.table-striped

  thead

    tr

      th Product Name

      th Quantity

      th Price

      th Total

      th status

  tbody

    - @order_items.each do |order_item|

      tr

        td= order_item.product.name

        td= order_item.quantity

        td= order_item.price

        td= order_item.price * order_item.quantity

        td= order_item.invoice_status

        / td= order_item.invoice_date

p Discount Applied: #{@dist = (@order.total_amount * 0.1)}

 

table.table.table-bordered.table-striped

  tbody

    tr

      td[colspan="3"] Total Amount:

      td= @order.total_amount - @dist

app/views/cart/pay.html.slim
  h1
    | Invoice
    
  = render "cart/table"
  br
  -if  @cart.total > 2000
    h3 
      |  &emsp;You got 10 % discount !!!! 
    h5 
      |  &emsp; &emsp;Thank you visit again...  
  -else
    h5 
      |  &emsp; &emsp;Thank you visit again...
  br
  = link_to "HOME" , root_path, class: "btn btn-outline-primary btn-lg"

app/views/cart/show2.html.slim
h1 Your Cart

 

- if @cart_items.present?

  table.table.table-bordered.table-striped

    thead

      tr

        th Name

        th Quantity

        th Price

        th Total

        th status

    tbody

      - @cart_items.each do |cart_item|

        tr

          td = cart_item.product.name

          td = cart_item.quantity

          td = cart_item.product.price

          td = cart_item.product.price * cart_item.quantity

          td = @cart.status

  .total-amount-box

    .total-amount

      strong Total Amount:

      span = @total_amount

 

  / Form to apply discount coupon

  = form_tag apply_discount_cart_path(@cart), method: :post do

    label for: :discount_code, class: 'form-label' do

      | Select a Discount Coupon:

    select name: 'discount_code', id: 'discount_code', class: 'form-select'

      option value=""

        | An empty option for no discount selected

      - @discount_coupons.each do |coupon|

        option value=coupon.code

          = coupon.name

      option value="summer30"

        | Summer 30% (summer30)

      option value="winter20"

        | Winter 20% (winter20)

    button type="submit" class="btn btn-primary" Apply Coupon

 

  / Form to pay the bill

  = form_with(url: pay_bill_cart_path(@cart), method: :post) do |form|

    = form.submit 'Pay Bill', class: 'btn btn-primary'

 

- else

  p Your cart is empty.

app/views/layouts/_footer.html.slim
footer
  .container
    .row
      .col-md-12.text-center
        p
            i
              | © 2023 BookShelf.com. All rights reserved.

app/views/products/_form.html.slim
.center-form
  = form_with(model: product, local: true) do |form|
    - if product.errors.any?
      #error_explanation
        .color:.red
          h2
            = pluralize(product.errors.count, "error")
            prohibited this product from being saved:
          ul
            - product.errors.full_messages.each do |message|
              li = message

    .form-group.mb-3
      = form.label :name
      = form.text_field :name, class: 'form-control form-control-sm'

    .form-group.mb-3
      = form.label :code
      = form.text_field :code, class: 'form-control form-control-sm'

    .form-group.mb-3
      = form.label :price
      = form.text_field :price, class: 'form-control form-control-sm'
    
    .form-group.mb-3
      = form.label :description
      = form.text_field :description, class: 'form-control form-control-sm'

    .form-group.mb-3
      = form.label :is_active
      = form.check_box :is_active
   
    .form-group.mb-3
      = form.label :cover_image
      = form.file_field :cover_image, class: 'form-control form-control-sm'

    .form-group.mt-3
      = form.submit class: "btn btn-primary "

= link_to "Back" , root_path, class: "btn btn-light"

app/views/products/_product.html.slim
.row

  - @products.each do |product|

    .col-md-3.mb-4

      .card.shadow

        .card-body

          - if product.cover_image.attached?

            = link_to product_path(product) do

            - if product.cover_image.attached?
                    = link_to product_path(product) do
                      = image_tag product.cover_image, width: '100',class: "img-thumbnail mx-auto d-block"
                      .overlay
                          .overlay-content
          h5.card-title.card-text.text-truncate.text-center.mt-2.mb-1  = product.name

          p.card-text.text-truncate.text-center.mt-2.mb-1 Code: #{product.code}

          p.card-text.text-muted.text-center.mb-3 Price: #{product.price} rs

          .d-grid.gap-2

          
            = form_with(url: cart_add_path) do |f|
              = f.hidden_field :id, value: product.id
              = f.number_field :quantity, value: 1, min: 1, class: 'quantity-input'
              = f.submit "Add To Cart"
             

            / = link_to 'Show', product, class: "btn btn-dark"

            - if policy(product).edit?

              = link_to 'EDIT', edit_product_path(product), class: "btn btn-info"

            - if policy(product).destroy?

              = link_to "REMOVE", product_path(product), data: {  method: :delete, confirm: "You want to delete?" }, class: "btn btn-danger"

       

p



 

 

 


















/ table.table-borderless
/     thead
/       tr
/         th
        
/           |  NAME  &emsp; 
        
        
       
/     tbody
/     .div
/       - if user_signed_in?
/         - @products.each_slice(2) do |product_group|
/           .row
/             - product_group.each do |product|
/               .col-md-6
/                 table
/                   tr
/                     td
/                       - if product.cover_image.attached?
/                         = link_to product_path(product) do
/                           = image_tag product.cover_image, width: '100'  
/                         br
/                         = link_to "Show", product_path(product), class: "btn btn-light"
                      
/                         - if policy(product).update?
/                           = link_to "Edit", edit_product_path(product), class: "btn btn-light"
                      
/                         = link_to "Download", download_pdf_product_path(product), class: "btn btn-light"
                      
/                         - if policy(product).destroy?
/                           = link_to "Delete", product_path(product), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"
/                         br
/                         br
/                           = form_with(url: cart_add_path) do |f|
/                             = f.hidden_field :id, value: product.id
/                             = f.number_field :quantity, value: 0, min: 1
/                             = f.submit "Add To Cart"
/                             =link_to "SHOW CART", cart_path, class: "btn btn-light btn-sm"

/                     / = product.name
/                     / = product.code
                  
/       - else
/         - @products.each_slice(2) do |product_group|
/           .row
/             - product_group.each do |product|
/               .col-md-6
/                 table
/                   tr
/                     td= product.name
/                     | &emsp; &emsp;
/                     td= product.code
/                     | &emsp; &emsp;
/                     td
/                       = image_tag product.cover_image, width: '150'

app/views/products/_review.html.slim
style 
    | div { max-width: 1200px; }
    | .reviews-container {max-width: 1200px;}
    | .reviews-container2 {max-width: 500px;}
    /= current_user.role =="admin" 
h2
    | Reviews :
    .reviews-container
      - @product.reviews.each_slice(3) do |reviews|
        .row
          - reviews.each do |review|
            .col-md-4
              .card.mb-3
                .card-body
                  p.card-text
                    strong
                    h3 
                      | &nbsp;Name :  
                      = review.user_name.capitalize

                  p.card-text
                    strong 
                      |  &emsp;Comment : 
                      = review.comments
                  p.card-text
                    strong 
                      |  &emsp;Rating : 
                      span.star-rating data-rating=review.rating
                      = review.rating 
div
    .reviews-container2
      h2
      | Add a review:
      = form_with model: [ @product, @product.reviews.build ] do |form|
          = form.hidden_field :product_id
          p  
              = form.hidden_field :user_name, value: current_user.profile&.first_name, readonly: true, class: 'form-control form-control-sm'      
              p 
            
              = form.label :rating, step: '0.5' 
              br
              = form.range_field :rating, in: 0..5, step: '0.5' , class: "rating-input"
              
              p
      
              p
              = form.label :comments
              br
              = form.text_field :comments, class: 'form-control form-control-sm'
              p
              = form.submit

javascript:

 document.addEventListener('DOMContentLoaded', () => {
  const ratingInput = document.querySelector('.rating-input');
  const ratingValue = document.createElement('span');
  ratingValue.classList.add('rating-value');
  ratingInput.after(ratingValue);

  ratingInput.addEventListener('input', (event) => {
    const rating = event.target.value;
    ratingValue.textContent = rating;
  });

  const starRatingElements = document.querySelectorAll('.star-rating');

  starRatingElements.forEach(element => {
    const elementRating = parseFloat(element.getAttribute('data-rating'));
    element.innerHTML = '';

      for (let i = 1; i <= 5; i++) {
        const star = document.createElement('span');
        if (i <= elementRating  ) {
          star.textContent = '\u2605'; // Full star
        } else if (i - 0.5 == elementRating) {
          star.textContent = '\u00BD'; // Half star
        } else {
          star.textContent = '\u2606'; // Empty star
        }
        element.appendChild(star);
        }
  });
 });

app/views/products/_reviewadmin.html.slim
style 
  | div { max-width: 1200px; }
  | .reviews-container {max-width: 1200px;}
  | .reviews-container2 {max-width: 600px;}

/= current_user.role =="admin" 
h2
  | Reviews :
  .reviews-container
    - @product.reviews.each_slice(3) do |reviews|
      .row
        - reviews.each do |review|
          .col-md-4
            .card.mb-3
              .card-body
                p.card-text
                  strong
                  h3 
                    | &nbsp;Name :  
                    = review.user_name.capitalize

                p.card-text
                  strong 
                    |  &emsp;Comment : 
                    = review.comments
                p.card-text
                  strong 
                    |  &emsp;Rating : 
                    span.star-rating data-rating=review.rating
                    = review.rating
                p
              div
                = link_to "Delete", product_review_path(@product.id, review.id), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger"
javascript: 
  document.addEventListener('DOMContentLoaded', () => {
  const starRatingElements = document.querySelectorAll('.star-rating');

  starRatingElements.forEach(element => {
    const elementRating = parseFloat(element.getAttribute('data-rating'));
    element.innerHTML = '';

    for (let i = 1; i <= 5; i++) {
      const star = document.createElement('span');
      if (i <= elementRating) {
        star.textContent = '\u2605'; // Full star
      } else if (i - 0.5 <= elementRating) {
        star.textContent = '\u00BD'; // Half star
      } else {
        star.textContent = '\u2606'; // Empty star
      }
      element.appendChild(star);
    }
  });
 });

app/views/products/show.html.slim
style
  | h1 { max-width: 600px; margin: auto; }
  | div { max-width: 1000px; margin: auto; }
  | .product-container { display: flex; justify-content: space-between; align-items: center; margin-top: 20px; }
  | .product-image { flex: 0 0 40%; }
  | .product-description { flex: 0 0 55%; padding-left: 20px; }

h1
  .product-container
    = @product.name

div
  .product-container
    .product-image
      = image_tag @product.cover_image, width: '300' if @product.cover_image.attached?

    .product-description
      br
      | code:
      = @product.code
      br
      br
      | description:
      = @product.description
      br
      br
      = form_with(url: cart_add_path) do |f|
        .add-to-cart
          = f.hidden_field :id, value: @product.id
          = f.number_field :quantity, value: 0, min: 1, class: 'quantity-input'
          = f.submit "Add To Cart", class: "btn btn-primary"
          = link_to "SHOW CART", cart_path, class: "btn btn-outline-primary"

  - if policy(@product).destroy?
      = render 'reviewadmin', review: @review
  - else
  
      = render 'review', review: @review
= link_to "Back" , root_path, class: "btn btn-light"
.product-container

app/views/users/_profile_fileds.html.slim
h3
  | Profile fields 
= f.fields_for :profile do |p|
  div
    = p.label :User_name ,style: "display: block"
    = p.text_field :first_name, class: 'form-control form-control-lg'
    br
  div
    = p.label :name ,style: "display: block"
    = p.text_field :last_name, class: 'form-control form-control-lg'
    br
  div
    = p.label :mobile_number ,style: "display: block"
    = p.number_field :mobile, class: 'form-control form-control-lg'
    br
  div
    = p.label :address ,style: "display: block"
    = p.text_area :address, class: 'form-control form-control-lg'
    br
  div
    = p.label :zip_code ,style: "display: block"
    = p.text_field :zip_code, class: 'form-control form-control-lg'
    br